source 'https://github.com/CocoaPods/Specs.git'
# xcodeproj 'TriviaRush/TriviaRush.xcodeproj'

platform :ios, '8.3'
pod 'ReactiveCocoa'
pod 'libextobjc'
pod 'Objection'
pod 'Mantle'
pod 'Masonry'
pod 'CocoaLumberjack'
pod 'AFNetworking-RACExtensions'
